# Generated by Django 5.2.11 on 2026-02-07 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='???????')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='???')),
            ],
            options={
                'verbose_name': '??????',
                'verbose_name_plural': '??????',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='??????')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='??????')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='?γ?????')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='?γ????')),
                ('credits', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='???')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='required_by', to='core.course', verbose_name='????γ?')),
            ],
            options={
                'verbose_name': '?γ?',
                'verbose_name_plural': '?γ?',
            },
        ),
        migrations.CreateModel(
            name='IndicatorPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='????????')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='???')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='???')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_points', to='core.graduationrequirement', verbose_name='??????????')),
            ],
            options={
                'verbose_name': '????',
                'verbose_name_plural': '????',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='CourseSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='??????')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='?γ?')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicatorpoint', verbose_name='????')),
            ],
            options={
                'verbose_name': '?γ???????',
                'verbose_name_plural': '?γ???????',
                'unique_together': {('course', 'indicator')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='indicator_points',
            field=models.ManyToManyField(related_name='courses', through='core.CourseSupport', to='core.indicatorpoint', verbose_name='????????'),
        ),
        migrations.AddField(
            model_name='graduationrequirement',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_requirements', to='core.major', verbose_name='??????'),
        ),
        migrations.AddField(
            model_name='course',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.major', verbose_name='??????'),
        ),
        migrations.CreateModel(
            name='TrainingObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='???????')),
                ('sequence', models.PositiveIntegerField(default=1, verbose_name='???')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_objectives', to='core.major', verbose_name='??????')),
            ],
            options={
                'verbose_name': '???????',
                'verbose_name_plural': '???????',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='ObjectiveSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='??????')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graduationrequirement', verbose_name='??????')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingobjective', verbose_name='???????')),
            ],
            options={
                'verbose_name': '?????????????',
                'verbose_name_plural': '?????????????',
                'unique_together': {('requirement', 'objective')},
            },
        ),
        migrations.AddField(
            model_name='graduationrequirement',
            name='training_objectives',
            field=models.ManyToManyField(related_name='supported_requirements', through='core.ObjectiveSupport', to='core.trainingobjective', verbose_name='???????????'),
        ),
    ]
