# Generated by Django 5.2.11 on 2026-02-12 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='coursesupport',
            options={'verbose_name': 'Course Support', 'verbose_name_plural': 'Course Support'},
        ),
        migrations.AlterModelOptions(
            name='graduationrequirement',
            options={'ordering': ['sequence'], 'verbose_name': 'Graduation Requirement', 'verbose_name_plural': 'Graduation Requirement'},
        ),
        migrations.AlterModelOptions(
            name='indicatorpoint',
            options={'ordering': ['sequence'], 'verbose_name': 'Indicator Point', 'verbose_name_plural': 'Indicator Point'},
        ),
        migrations.AlterModelOptions(
            name='objectivesupport',
            options={'verbose_name': 'Objective Support', 'verbose_name_plural': 'Objective Support'},
        ),
        migrations.AlterModelOptions(
            name='trainingobjective',
            options={'ordering': ['sequence'], 'verbose_name': 'Training Objective', 'verbose_name_plural': 'Training Objective'},
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Course Category'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Course Code'),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Credits'),
        ),
        migrations.AlterField(
            model_name='course',
            name='indicator_points',
            field=models.ManyToManyField(related_name='courses', through='core.CourseSupport', to='core.indicatorpoint', verbose_name='Indicator Points'),
        ),
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.major', verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', to='core.course', verbose_name='Prerequisites'),
        ),
        migrations.AlterField(
            model_name='coursesupport',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='coursesupport',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indicatorpoint', verbose_name='Indicator'),
        ),
        migrations.AlterField(
            model_name='coursesupport',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_requirements', to='core.major', verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='sequence',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='graduationrequirement',
            name='training_objectives',
            field=models.ManyToManyField(related_name='supported_requirements', through='core.ObjectiveSupport', to='core.trainingobjective', verbose_name='Supported Training Objectives'),
        ),
        migrations.AlterField(
            model_name='indicatorpoint',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='indicatorpoint',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicator_points', to='core.graduationrequirement', verbose_name='Graduation Requirement'),
        ),
        migrations.AlterField(
            model_name='indicatorpoint',
            name='sequence',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequence'),
        ),
        migrations.AlterField(
            model_name='indicatorpoint',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Major Code'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Major Name'),
        ),
        migrations.AlterField(
            model_name='objectivesupport',
            name='objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trainingobjective', verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='objectivesupport',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.graduationrequirement', verbose_name='Requirement'),
        ),
        migrations.AlterField(
            model_name='objectivesupport',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='trainingobjective',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='trainingobjective',
            name='major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_objectives', to='core.major', verbose_name='Major'),
        ),
        migrations.AlterField(
            model_name='trainingobjective',
            name='sequence',
            field=models.PositiveIntegerField(default=1, verbose_name='Sequence'),
        ),
    ]
