# Generated by Django 5.2.11 on 2026-02-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_course_options_alter_coursesupport_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Semester'),
        ),
    ]
