# Generated by Django 5.2.11 on 2026-03-04 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesupport',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supports', to='core.course', verbose_name='Course'),
        ),
    ]
