# Generated by Django 6.0.3 on 2026-03-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_coursesupport_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='major',
            name='core_courses_text',
            field=models.TextField(blank=True, null=True, verbose_name='主干课程文本'),
        ),
        migrations.AddField(
            model_name='major',
            name='core_disciplines',
            field=models.TextField(blank=True, null=True, verbose_name='主干学科'),
        ),
        migrations.AddField(
            model_name='major',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学位'),
        ),
        migrations.AddField(
            model_name='major',
            name='degree_condition',
            field=models.TextField(blank=True, null=True, verbose_name='学士学位授予条件'),
        ),
        migrations.AddField(
            model_name='major',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='学制'),
        ),
        migrations.AddField(
            model_name='major',
            name='graduation_condition',
            field=models.TextField(blank=True, null=True, verbose_name='毕业条件'),
        ),
        migrations.AlterField(
            model_name='major',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='专业代码'),
        ),
        migrations.AlterField(
            model_name='major',
            name='name',
            field=models.CharField(max_length=100, verbose_name='专业名称'),
        ),
    ]
